# Generated by Django 2.2.2 on 2021-07-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
